# Generated by Django 3.2.7 on 2021-10-14 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science')], max_length=5)),
                ('code_team_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('position', models.CharField(choices=[('fwd', 'Foward'), ('mid', 'Midfield'), ('def', 'Defence'), ('gk', 'Goal keeper')], default=2, max_length=3)),
                ('team', models.CharField(blank=True, choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science')], max_length=5)),
                ('status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.coach')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('wk1', 'week1'), ('wk2', 'week2'), ('wk3', 'week3'), ('wk4', 'week4'), ('wk5', 'week5'), ('wk6', 'week6'), ('wk7', 'week7'), ('wk8', 'week8'), ('wk9', 'week9'), ('wk10', 'week10')], default=1, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ManyToManyField(to='player.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('minutes_played', models.IntegerField()),
                ('yellowcard', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=10)),
                ('redcard', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=10)),
                ('captain', models.BooleanField()),
                ('weekly_points', models.IntegerField(default=1)),
                ('total_points', models.IntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.weeks')),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ['total_points'],
            },
        ),
        migrations.CreateModel(
            name='PlayerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
        ),
    ]
