# Generated by Django 3.2.7 on 2021-10-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeks',
            options={'verbose_name_plural': 'Weeks'},
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
