# Generated by Django 3.2.7 on 2021-10-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_alter_coach_code_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='code_team_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
