# Generated by Django 3.2.7 on 2021-10-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20211019_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='assists',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='goals',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='minutes_played',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='redcard',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='point',
            name='yellowcard',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default=0, max_length=10),
        ),
    ]
