# Generated by Django 3.2.7 on 2021-10-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20211019_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='assists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='goals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
