# Generated by Django 3.2.7 on 2021-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20211022_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteam',
            name='team',
            field=models.ManyToManyField(max_length=12, to='player.Player'),
        ),
    ]
