# Generated by Django 3.2.7 on 2021-11-07 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0012_auto_20211028_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='code_team_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.CharField(choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science')], max_length=5),
        ),
    ]
