# Generated by Django 3.2.7 on 2021-11-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_auto_20211107_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.CharField(choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science'), ('chem', 'Chemical Engineering')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(choices=[('cpas', 'College of pure and applied science'), ('coe', 'College of Engineering'), ('coe', 'College of Engineering'), ('cbs', 'College of Business and Social Science')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science'), ('chem', 'Chemical Engineering')], max_length=5),
        ),
    ]
