# Generated by Django 3.2.7 on 2021-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20211107_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(choices=[('cpas', 'College of pure and applied science'), ('coe', 'College of Engineering'), ('cas', 'College of Agricultural Science'), ('cbs', 'College of Business and Social Science')], max_length=200, null=True),
        ),
    ]
