# Generated by Django 3.2.7 on 2021-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_alter_player_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userteam',
            name='team',
        ),
        migrations.AddField(
            model_name='userteam',
            name='attackers',
            field=models.ManyToManyField(to='player.Player'),
        ),
    ]
