# Generated by Django 3.2.7 on 2021-11-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_auto_20211125_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userteam',
            name='defenders',
            field=models.ManyToManyField(related_name='defenders', to='player.Player'),
        ),
        migrations.AddField(
            model_name='userteam',
            name='midfielders',
            field=models.ManyToManyField(related_name='midfielders', to='player.Player'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='attackers',
            field=models.ManyToManyField(related_name='attackers', to='player.Player'),
        ),
    ]
