# Generated by Django 3.2.7 on 2021-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_userteam_goalkeeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.CharField(choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science'), ('chem', 'Chemical Engineering'), ('bus', 'Business Admin')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, choices=[('cve', 'Civil Engineering'), ('mch', 'Mechanical Engineering'), ('csc', 'Computer Science'), ('abe', 'Agric and Biosystems Engineering'), ('sip', 'Sociology, International reltions and political science'), ('sos', 'School of Science'), ('phy', 'Physical Sience'), ('eie', 'Electrical Information Engineering'), ('acc', 'Accounting'), ('eco', 'Economics'), ('mcom', 'Mass Communication'), ('aqua', 'Agric Extention'), ('cas', 'Animal Science'), ('chem', 'Chemical Engineering'), ('bus', 'Business Admin')], max_length=5),
        ),
    ]
